redhat: Reduce email spam from kinit-redhat script
Keep quiet when there is no active VPN connection and no ticket
to renew.

diff --git a/roles/redhat/files/kinit-redhat b/roles/redhat/files/kinit-redhat
--- a/roles/redhat/files/kinit-redhat
+++ b/roles/redhat/files/kinit-redhat
@@ -5,5 +5,9 @@ then
     # Use LOGNAME instead of USER so this works as a cron job.
     pass show redhat.com | head --lines 1 | kinit ${LOGNAME}@IPA.REDHAT.COM > /dev/null && klist
 else
-    echo "Cannot renew Red Hat Kerberos token: no active VPN connection" >&2
+    # Keep quiet if there's no ticket cache file to avoid needless cron emails.
+    if [ -f /tmp/krb5cc_$(id --user) ]
+    then
+        echo "Cannot renew Red Hat Kerberos ticket: no active VPN connection" >&2
+    fi
 fi
